name: Super-Linter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for VALIDATE_ALL_CODEBASE

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6  # Use latest version
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: "true"
          VALIDATE_PYTHON: "true"
          VALIDATE_TERRAFORM: "true"
          VALIDATE_ANSIBLE: "true"
          VALIDATE_RUBY: "true"
          VALIDATE_YAML: "true"
          VALIDATE_JSON: "true"
          VALIDATE_MARKDOWN: "true"
          VALIDATE_BASH: "true"
          VALIDATE_DOCKERFILE_HADOLINT: "true"  # Corrected variable
